# Page settings

baseURL = "https://ArrogantL.github.io/"
languageCode = "en"
title = "Hi, I'm Jinglong Gao"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"
publishDir = "docs"





[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Jinglong Gao"
        tagline = "PhD Student"
        avatar = "me.png"







    [params.contact]
        enable = true
        location = "Harbin"

        #[[params.contact.list]]
        #icon = "fas fa-phone-square"
        #url = "tel:#"
        #text = "0123 4567 890"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:jlgao@ir.hit.edu.cn"
        text = "Mail"
        [[params.contact.list]]
        icon = "fab fa-google"
        url = "https://scholar.google.com/citations?user=jaVvkHIAAAAJ&hl=zh-CN"
        text = "Google Scholar"






    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Language"
        [[params.skills.list.items]]
        details = "Python/Java/C++/C"      

        [[params.skills.list]]
        title = "Platform"
        [[params.skills.list.items]]
        details = "Pytorch/Tensorflow"

 







    [params.education]
        enable = true

        [[params.education.list]]
        degree = "PhD - Computer Science"
        university = "Harbin Institute of Technology"
        dates = "2021 - Present"
        [[params.education.list]]
        degree = "Visiting Student"
        university = "iFLYTEK, AI Lab"
        dates = "2023 - 2024"
        [[params.education.list]]
        degree = "Visiting Student"
        university = "Huawei Cloud, AI Lab"
        dates = "2021 - 2022"
        [[params.education.list]]
        degree = "Master - Computer Science"
        university = "Harbin Institute of Technology"
        dates = "2020 - 2021"
        [[params.education.list]]
        degree = "Bachelor - Computer Science"
        university = "Harbin Institute of Technology"
        dates = "2016 - 2020"






#    [params.awards]
#        enable = true
#
#        [[params.awards.list]]
#        name = "2021 Best Paper Award for IEEE Multimedia"
#        body = "IEEE Computer Society Publications Board"
#        date = "2021"




    [params.languages]
        enable = false

        [[params.languages.list]]
        name = "Chinese"
        [[params.languages.list]]
        name = "English"









    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Causal Reasoning"
        [[params.interests.list]]
        name = "Large Language Models"









    [params.summary]
        enable = true
        text = "I'm a Ph.D. student in Research Center for Social Computing and Information Retrieval(SCIR), at Harbin Institute of Technology (HIT, China). I am co-advised by Prof. Ting Liu and Prof. Xiao Ding. My research interests include causal reasoning and large language models."








    [params.experience]
        enable = false

        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "2019 - Present"
        company = "Google"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."
        [[params.experience.list.items]]
        details = "Etiam ultricies nisi vel augue."

        [[params.experience.list]]
        title = "Lead Software Developer"
        dates = "2016 - 2019"
        company = "Apple"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."

        [[params.experience.list]]
        title = "Senior Software Developer"
        dates = "2014 - 2016"
        company = "Dropbox"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Senior Developer"
        dates = "2013 - 2014"
        company = "Uber"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

        [[params.experience.list]]
        title = "Backend Developer"
        dates = "2014 - 2016"
        company = "Amazon"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Frontend Developer"
        dates = "2013 - 2014"
        company = "Startup"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."











    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."





    [params.information]
        enable = true


        [[params.information.list]]

        title = "Towards Generalizable and Faithful Logic Reasoning over Natural Language via Resolution Refutation"
        name = "Zhouhao Sun, Xiao Ding, Li Du, Bibo Cai, Jinglong Gao, Ting Liu, Bing Qin"
        publisher = "Coling 2024"
        href = "https://arrogantl.github.io"

        details = "Large language models (LLMs) have achieved significant performance in various natural language reasoning tasks. However, they still struggle with performing first-order logic reasoning over formal logical theories expressed in natural language. This is because the previous LLMs-based reasoning systems have the theoretical incompleteness issue. As a result, it can only address a limited set of simple reasoning problems, which significantly decreases their generalization ability. To address this issue, we propose a novel framework, named Generalizable and Faithful Reasoner (GFaiR), which introduces the paradigm of resolution refutation. Resolution refutation has the capability to solve all first-order logic reasoning problems by extending reasoning rules and employing the principle of proof by contradiction, so our system’s completeness can be improved by introducing resolution refutation. Experimental results demonstrate that our system outperforms previous works by achieving state-of-the-art performances in complex scenarios while maintaining performances in simple scenarios. Besides, we observe that GFaiR is faithful to its reasoning process."

        [[params.information.list]]

        title = "Is ChatGPT a Good Causal Reasoner? A Comprehensive Evaluation"
        name = "Jinglong Gao, Xiao Ding, Bing Qin, Ting Liu"
        publisher = "Findings of EMNLP 2023"
        href = "https://aclanthology.org/2023.findings-emnlp.743/"
    
        details = "Causal reasoning ability is crucial for numerous NLP applications. Despite the impressive emerging ability of ChatGPT in various NLP tasks, it is unclear how well ChatGPT performs in causal reasoning. In this paper, we conduct the first comprehensive evaluation of the ChatGPT’s causal reasoning capabilities. Experiments show that ChatGPT is not a good causal reasoner, but a good causal interpreter. Besides, ChatGPT has a serious hallucination on causal reasoning, possibly due to the reporting biases between causal and non-causal relationships in natural language, as well as ChatGPT’s upgrading processes, such as RLHF. The In-Context Learning (ICL) and Chain-of-Thought (COT) techniques can further exacerbate such causal hallucination. Additionally, the causal reasoning ability of ChatGPT is sensitive to the words used to express the causal concept in prompts, and close-ended prompts perform better than open-ended prompts. For events in sentences, ChatGPT excels at capturing explicit causality rather than implicit causality, and performs better in sentences with lower event density and smaller lexical distance between events."
#        details = "Despite the impressive emerging ability of ChatGPT in various NLP tasks, it is unclear how well ChatGPT performs in causal reasoning. In this paper, we conduct the first comprehensive evaluation of the ChatGPT's causal reasoning capabilities."

        [[params.information.list]]

        title = "Discrimloss: a universal loss for hard samples and incorrect samples discrimination"
        name = "Tingting Wu, Xiao Ding, Hao Zhang, Jinglong Gao, Minji Tang, Li Du, Bing Qin, Ting Liu"
        publisher = "IEEE Transactions on Multimedia 2023"
        href = "https://arxiv.org/pdf/2208.09884"

#        details = "Previous curriculum learning work takes incorrect samples as generic hard ones without discriminating between hard samples and incorrect samples. Indeed, a model should learn from hard samples to promote generalization rather than overfit to incorrect ones. In this paper, we address this problem by appending a novel loss function DiscrimLoss."
        details = "Given data with label noise (i.e., incorrect data), deep neural networks would gradually memorize the label noise and impair model performance. To relieve this issue, curriculum learning is proposed to improve model performance and generalization by ordering training samples in a meaningful (e.g., easy to hard) sequence. Previous work takes incorrect samples as generic hard ones without discriminating between hard samples (i.e., hard samples in correct data) and incorrect samples. Indeed, a model should learn from hard samples to promote generalization rather than overfit to incorrect ones. In this paper, we address this problem by appending a novel loss function DiscrimLoss, on top of the existing task loss. Its main effect is to automatically and stably estimate the importance of easy samples and difficult samples (including hard and incorrect samples) at the early stages of training to improve the model performance. Then, during the following stages, DiscrimLoss is dedicated to discriminating between hard and incorrect samples to improve the model generalization. Such a training strategy can be formulated dynamically in a self-supervised manner, effectively mimicking the main principle of curriculum learning. Experiments on image classification, image regression, text sequence regression, and event relation reasoning demonstrate the versatility and effectiveness of our method, particularly in the presence of diversified noise levels."

        [[params.information.list]]

        title = "(Demo) Chinese-English Causality Event Generation Demonstration System"
        name = "Jinglong Gao, Zhongyang Li, Xiao Ding"
        publisher = "SCIR 2020"
        href = "http://221.207.166.58:8004"

        details = "The demonstration system is capable of generating multiple possible causes and effects of input events. The causal relationships between events are essential pieces of knowledge in the causal graph. Existing causal knowledge acquisition mostly relies on extraction methods, such as extracting causal event pairs from text through pattern matching, statistical machine learning, or deep learning methods. Extraction-based methods involve acquiring and recording existing knowledge from the world, rather than creating new knowledge. Therefore, we propose a new approach to acquiring causal knowledge—based on generative methods—as an important complement to traditional extraction-based causal knowledge acquisition."




    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/ArrogantL"
        title = "ArrogantL"
 





